### ISSUE TITLE
RNP adapter / integration

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enmail#36] opened 2018-04-30 23:23 UTC
From @skalee #31 :
> [...] are RNP and GPG homedirs compatible? That is, can I generate that homedir with GPG and use with RNP, and vice versa?

@dewyatt can give you a much better answer! 😉

**Comment by dewyatt** [comment] 2018-05-01 00:07
Yes and no. There are some incompatibilities here and there to be aware of.

The issues I can think of would be:
* Certain types of keys coming from a GnuPG 2.1+ (`private-keys-v1.d`) will not be usable in RNP due to https://github.com/riboseinc/rnp/issues/540 and also https://github.com/riboseinc/rnp/issues/453.
* GnuPG may not accept signing subkeys from RNP due to https://github.com/riboseinc/rnp/issues/373.
* RNP supports some ciphers and things that GnuPG does not (and probably vice versa).

**Comment by skalee** [comment] 2018-07-25 03:06
I believe it can be closed as a duplicate of #53.

**Closed by skalee** 2018-07-25 03:06 UTC
Labels: question
